apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: furiko
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name: ""
    namespace: furiko
    server: "https://kubernetes.default.svc"
  source:
    path:
    repoURL: "https://github.com/furiko-io/furiko/releases/latest/download/furiko-execution.yaml"
    targetRevision: HEAD
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
